### PR TITLE
bring aws-cli current

### PR DESCRIPTION
**Pull request by paul-krohn**
And get it to build on python 3. 

For: [W-7099494](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B000000794EzIAI/view)

### CODE REVIEW

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by instantlinux** [comment]
Do we still need any customizations in this codebase? Can we archive it and use the public version?

**Review by ghost — APPROVED** [review]
OMG.  Can we delete this yet and just use upstream?

**Comment by paul-krohn** [comment]
If someone is in the mood to convert this to an fpm-recipe or similar, go for it.

**Pull request merged**
