### PR TITLE
Conflict resolution

### PR DESCRIPTION
**Pull request by paul-krohn**
2nd PR: merge develop (which is the branch upstream merges to) with our master (which we build from) so I can get a PR build, then merge & get ... a package. 🤞

### CODE REVIEW

**Comment by dllopis-sfdc** [comment]
How would I validate that this is a proper fork from aws/aws-cli? What commit/release is it forked from?

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
retest this please

**Comment by paul-krohn** [comment]
@dllopis-sfdc It was branched from 7c6e8d2a48bc88fee3a289cb7658bdb906086677, this PR should bring us up to cb048b34304eaba65d450b790fb1798da725bd0b.

**Review by ghost — APPROVED** [review]
Trusting that this has been tested.

**Review by dllopis-sfdc — APPROVED** [review]

**Pull request merged**
